apiVersion: v1
kind: Service
metadata:
  name: user-account-service
  labels:
    app: user-account-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: user-account-service
---
apiVersion: v1
kind: Service
metadata:
  name: user-account-service-nodeport
  labels:
    app: user-account-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8081
    nodePort: 30081
    protocol: TCP
    name: http
  selector:
    app: user-account-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-account-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: user-account-service.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: user-account-service
            port:
              number: 80

