apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8090
      protocol: TCP
      name: http
  selector:
    app: user-service
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-nodeport
  labels:
    app: user-service
spec:
  type: NodePort
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30090
      protocol: TCP
      name: http
  selector:
    app: user-service